modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/daPoseidonGuy/strawgolem"
[[mods]]
    modId = "strawgolem"
version = "1.16-1.91"
displayName = "Straw Golem"
    credits="nivoridocs, for making the original mod\nFrenderman, for making the updated golem model, testing and design ideas"
    authors="CommodoreThrawn"
    description='''
    Adds a straw golem to help with farming
    '''