name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: "Setup JDK 11"
        uses: actions/setup-java@v2
        with: { distribution: "adopt", java-version: "11" }
      - name: "Build with Gradle"
        id: build
        run: "chmod +x gradlew && ./gradlew build"
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: Forge
          path: "build/libs"